[package]
name = "saito-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.17.0", features = ["sync", "tokio-macros", "test-util", "macros", "tracing"] }
secp256k1 = { version = "0.24.0", features = ["rand", "bitcoin_hashes", "global-context", "serde"] }
getrandom = { version = "0.2.4", features = ["js"] }
rand = { version = "0.8.4", features = ["getrandom"] }
pretty_env_logger = "0.4"
log = "0.4.14"
blake3 = { version = "1.2.0", features = ["rayon"] }
base58 = "0.2.0"
aes = "0.7.5"
block-modes = "0.8.1"
merkle = "1.11.0"
#bigint = "4.4.3"
serde = { version = "1.0.136", features = ["derive"] }
serde_with = "1.12.0"
hex = "0.4.3"
ahash = "0.8.0"
num-derive = "0.3.3"
num-traits = "0.2.14"
async-recursion = "1.0.0"
rayon = "1.5.1"
async-trait = "0.1.52"
primitive-types = "0.11.1"

[dev-dependencies]
serial_test = "0.9.0"
tokio = { version = "1.17.0", features = ["full"] }
futures = { version = "0.3.21" }
criterion = { version = "0.3.6", features = ["default", "html_reports"] }

[features]
locking-logs = []

[[bench]]
name = "benches"
harness = false

[profile.release]
debug = true
