[package]
name = "saito-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.17.0", features = ["sync"] }
secp256k1 = { version = "0.20.3", features = ["rand", "bitcoin_hashes", "global-context", "serde"] }
getrandom = { version = "0.2.4", features = ["js"] }
rand = { version = "0.8.4", features = ["getrandom"] }
pretty_env_logger = "0.4"
log = "0.4.14"
blake3 = { version = "1.2.0", features = ["rayon"] }
base58 = "0.2.0"
aes = "0.7.5"
block-modes = "0.8.1"
merkle = "1.11.0"
bigint = "4.4.3"
serde = { version = "1.0.136", features = ["derive"] }
serde_with = "1.12.0"
hex = "0.4.3"