[package]
name = "saito-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
saito-core = { path = "../saito-core" }
tokio = { version = "1.17.0" }
tungstenite = { version = "0.17.2" }