[package]
name = "saito-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
saito-core = { path = "../saito-core" }
tokio = { version = "1.21.1", features = ["full", "tracing"] }
tungstenite = { version = "0.17.3" }
tokio-tungstenite = "0.17.2"
tracing = "0.1.36"
pretty_env_logger = "0.4.0"
async-trait = "0.1.57"
lazy_static = "1.4.0"
figment = { version = "0.10.7", features = ["json"] }
futures = { version = "0.3.24", default-features = false }
rand = "0.8.5"
rayon = "1.5.3"
ahash = "0.8.0"
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
hex = "0.4.3"
warp = "0.3.2"
reqwest = "0.11.12"
base64 = "0.13.0"
ctrlc = { version = "3.2.3", features = ["termination"] }
#tracing-flame="0.2.0"
serde = { version = "1.0.144", features = ["derive"] }

[dev-dependencies]
serial_test = "0.9.0"
ctor = "0.1.23"
criterion = "0.4.0"

[profile.dev]
panic = "unwind"

[features]
default= []
locking-logs = ["saito-core/locking-logs"]
with-stats = ["saito-core/with-stats"]

[profile.release]
debug = true
