[package]
name = "saito-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
saito-core = { path = "../saito-core" }
tokio = { version = "1.17.0", features = ["full"] }
tungstenite = { version = "0.17.2" }
tokio-tungstenite = "0.17.1"
log = "0.4.14"
pretty_env_logger = "0.4.0"
async-trait = "0.1.52"
lazy_static = "1.4.0"
figment = { version = "0.10.6", features = ["json"] }
futures = { version = "0.3.21", default-features = false }
rand = "0.8.5"
rayon = "1.5.2"
ahash = "0.7.6"

[dev-dependencies]
serial_test = "0.6.0"
ctor = "0.1.22"