[package]
name = "saito-wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
saito-core = { path = "../saito-core" }
wasm-bindgen = { version = "0.2.83", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4.33"
serde = { version = "1.0.152", features = ["derive"] }
web-sys = "0.3.60"
async-trait = "0.1.61"
hex = "0.4.3"
tokio = "1.24.1"
js-sys = "0.3.60"
lazy_static = "1.4.0"
console_log = { version = "0.2.0", features = ["color"] }
log = "0.4.17"
getrandom = { version = "0.2.8", features = ["js", "std"] }
rand = { version = "0.8.5", features = ["getrandom"] }
secp256k1 = { version = "0.25.0", features = ["bitcoin_hashes", "global-context", "serde"] }
base58 = "0.2.0"
figment = { version = "0.10.8", features = ["json"] }
serde_json = "1.0.91"
