[package]
name = "saito-wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
saito-core = { path = "../saito-core" }
wasm-bindgen = { version = "0.2.80", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4.30"
serde = { version = "1.0.137", features = ["derive"] }
web-sys = "0.3.57"
async-trait = "0.1.56"
hex = "0.4.3"
tokio = "1.18.2"
js-sys = "0.3.57"
lazy_static = "1.4.0"