[package]
name = "saito-wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
saito-core = { path = "../saito-core" }
wasm-bindgen = { version = "0.2.79", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4.29"
serde = { version = "1.0", features = ["derive"] }
web-sys = "0.3.56"
#async-trait = "0.1.52"
hex = "0.4.3"
tokio = "1.17.0"