name: issuance-test

on:
  push:
    branches: [ feature/315/saito-e2e ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout SLR
        uses: actions/checkout@v2
        with:
          repository: 'SaitoTech/saito-lite-rust'
          path: 'slr'

      - name: update package.json
        run: npm update saito-js
        working-directory: 'slr'

      - name: npm install
        run: npm install
        working-directory: 'slr'

      - name: create ssh keys
        run: echo "$CI_SSH_PRIVATE_KEY" >> ~/CI_KEY
        working-directory: 'slr'
        env:
          CI_SSH_PRIVATE_KEY: ${{ secrets.CI_SSH_PRIVATE_KEY }}

      - name: print size of key
        run: ls -l ~/CI_KEY
        working-directory: 'slr'

      - name: create directory
        run: mkdir data/blocks
        working-directory: 'slr'

      - name: copy blocks in prod-services into data/blocks folder
        run: rsync -avP -e "ssh -i ~/CI_KEY" root@prod-services.saito.io:/opt/saito/data/blocks/ data/blocks/
        working-directory: 'slr'

      - name: run issuance file generation
        run: ts-node gen-issuance.ts

      - name: check for generated issuance file
        uses: andstor/file-existence-action@v3
        with:
          files: "data/issuance.file"
