name: Publish-Saito-Wasm

on:
  push:
    branches: [ prod, develop ] # remove develop after testing the script
#  workflow_run:
#    workflows: [ "Build Rust" ]
#    types: [ completed ]
#    branches: [ release/*** ]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    #    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - name: Install npm packages
        run: npm install
        working-directory: saito-wasm

      - name: Publish package
        run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: saito-wasm
